// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCaptureDevices() {
  return window['go']['main']['App']['GetCaptureDevices']();
}

export function GetData() {
  return window['go']['main']['App']['GetData']();
}

export function StartCapture(arg1) {
  return window['go']['main']['App']['StartCapture'](arg1);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
