// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCaptureDevices():Promise<Array<string>>;

export function GetData():Promise<Array<number>>;

export function StartCapture(arg1:string):Promise<void>;

export function StopCapture():Promise<void>;
